name: auto-assign-defaults
description: "Assigns default PR metadata: title-based labels, D-day by code size, PR author as assignee, and random reviewers."
branding:
  icon: check-circle
  color: blue

inputs: {}

runs:
  using: docker
  image: Dockerfile